import Head from 'next/head'
import Image from 'next/image'
import Footer from './comps/footer'
import Landing from './comps/landing'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import ProductsList from './comps/productlist';
import PRODUCTS from '../data.js';

export default function Home() {
  return (
    <>
      <Head>
        <title>Clogtopia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Landing />
          <Container maxWidth="lg">
            <ProductsList products={PRODUCTS} />
          </Container>
          <Footer />
        </div>
      </main>
    </>
  )
}