import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ScrollingBar from './comps/scrollingbar'
import Navbar from './comps/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Clogtopia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ScrollingBar>
          <span>FREE SHIPPING ON U.S. ORDERS OVER $100 + INTL ORDER OVER $200</span>
        </ScrollingBar>
      </div>
      <Navbar />
      <main className={styles.main}>
      </main>
    </>
  )
}
